export const details = [
    {
        PXC: [
            {
                id: "PXC1",
                name: "Cristiano Ronaldo",
                img: "./src/img/ronaldo-poster2",
                collection: "PLAYERS X CLUBS",
                data: "Juventus",
                Price: 259,
            },
            {
                id: "PXC2",
                name: "Jude bellingham",
                img: "./src/img/NEWDROP/Jude Bellingham Madrid.jpg",
                collection: "PLAYERS X CLUBS",
                data: "Real madrid",
                Price: 309,
            },
            {
                id: "PXC3",
                name: "Thierry Henry",
                img: "./src/img/NEWDROP/Henry X arsenal.jpg",
                collection: "PLAYERS X CLUBS",
                data: "Arsenal",
                Price: 179,
            },
            {
                id: "PXC4",
                name: "Julian Alvarez",
                img: "./src/img/NEWDROP//Julian Alvarez x Manchester city.jpg",
                collection: "PLAYERS X CLUBS",
                data: "Manchester City",
                Price: 279,
            },
            {
                id: "PXC5",
                name: "UNITED players",
                img: "./src/img/NEWDROP/MANUNITED.jpg",
                collection: "PLAYERS X CLUBS",
                data: "Manchester United",
                Price: 179,
            },
            {
                id: "PXC6",
                name: "Erling Haaland",
                img: "./src/img/NEWDROP/Erling Haaland x mancity.jpg",
                collection: "PLAYERS X CLUBS",
                data: "Manchester City",
                Price: 179,
            },
            {
                id: "PXC7",
                name: "SON",
                img: "./src/img/NEWDROP/SON X SPURS.jpg",
                collection: "PLAYERS X CLUBS",
                data: "Spurs",
                Price: 309,
            },
            {
                id: "PXC8",
                name: "RONALDO",
                img: "./src/img/ronaldo-poster3.jpg",
                collection: "PLAYERS X CLUBS",
                data: "JUVENTUS",
                Price: 279,
            },
        ],
        CARS: [
            {
                id: "CAR1",
                name: "Dodge Charger ",
                img: "src/img/NEWDROP/Dodge Charger.png",
                collection: "CARS",
                data: "NISSAN",
                Price: 179,
            },
            {
                id: "CAR2",
                name: "Honda Accord",
                img: "./src/img/NEWDROP/Honda Accord.png",
                collection: "CARS",
                data: "HONDA",
                Price: 179,
            },
            {
                id: "CAR3",
                name: "Honda S2000",
                img: "./src/img/NEWDROP/Honda S2000.png",
                collection: "CARS",
                data: "HONDA",
                Price: 179,
            },
            {
                id: "CAR4",
                name: "Nissan Nismo",
                img: "./src/img/NEWDROP/nisaan.png",
                collection: "CARS",
                data: "NISSAN",
                Price: 179,
            },
            {
                id: "CAR5",
                name: "Nissan Skyline",
                img: "./src/img/NEWDROP/nissan skyline.png",
                collection: "CARS",
                data: "NISSAN",
                Price: 249,
            },
            {
                id: "CAR6",
                name: "Porsche 911",
                img: "./src/img/NEWDROP/Porsche 911.png",
                collection: "CARS",
                data: "PORSCHE",
                Price: 179,
            },
            {
                id: "CAR7",
                name: "Porsche 934",
                img: "./src/img/NEWDROP/porsche 934.png",
                collection: "CARS",
                data: "PORSCHE",
                Price: 179,
            },
            {
                id: "CAR8",
                name: "Porsche 911 GT2",
                img: "./src/img/NEWDROP/Porsche.png",
                collection: "CARS",
                data: "PORSCHE",
                Price: 179,
            },
        ]
    }
]